site_name: Download Platform
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
  icon:
    admonition:
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
